### Registro de Usuario
POST http://127.0.0.1:8000/api/v1/auth/register
Accept: application/json
Content-Type: application/json

{
    "name": "javier",
    "email": "javier@mail.com",
    "password": "javier54321",
    "password2": "javier54321"
}

### Login

POST http://127.0.0.1:8000/api/v1/auth/login
Accept: application/json
Content-Type: application/json

{
    "email": "javier@mail.com",
    "password": "javier54321"
}

### PERFIL
GET http://127.0.0.1:8000/api/v1/auth/profile
Accept: application/json
Authorization: Bearer 6|Lv7jGjIaTXS6bvMrgwvEnjsMkvGnGg7c5tQzOcLp17a561bf

### LOGOUT
POST http://127.0.0.1:8000/api/v1/auth/logout
Accept: application/json
Authorization: Bearer 6|Lv7jGjIaTXS6bvMrgwvEnjsMkvGnGg7c5tQzOcLp17a561bf
