GET http://127.0.0.1:8000/api/producto?limit=1000&page=1&search=
Authorization: Bearer 1|9BHOmOJhUsgqlNwFedRKEafLTmkbFeqRwUTc5sCC9c2b8315
Accept: application/json
### Guardar Producto

POST http://127.0.0.1:8000/api/producto
Authorization: Bearer 1|9BHOmOJhUsgqlNwFedRKEafLTmkbFeqRwUTc5sCC9c2b8315
Content-Type: application/json
Accept: application/json

{
    "nombre": "Juego de Sillas DE MADERA",
    "categoria_id": 3,
    "descripcion": "Sillas de madera",
    "precio_venta": "198.99",
    "estado": true
}

### Mostrar
GET http://127.0.0.1:8000/api/producto/3
Authorization: Bearer 1|9BHOmOJhUsgqlNwFedRKEafLTmkbFeqRwUTc5sCC9c2b8315
Accept: application/json

### Modificar

PUT http://127.0.0.1:8000/api/producto/3
Authorization: Bearer 5|I64pRWtmUo1z7Aq1SvKK9eAl5n76QhgqEWDrjCxR1f06f0cd
Accept: application/json
Content-Type: application/json

{
  "nombre": "PARLANTES MODIFICADO",
  "descripcion": "Parlantes NUEVOS por modificar",
  "marca": "ABC",
  "precio_venta": "500.99",
  "estado": 1,
  "categoria_id": 2,
  "created_at": "2026-02-12T23:55:40.000000Z",
  "updated_at": "2026-02-12T23:55:40.000000Z"
}

### Eliminar
DELETE http://127.0.0.1:8000/api/producto/3
Authorization: Bearer 5|I64pRWtmUo1z7Aq1SvKK9eAl5n76QhgqEWDrjCxR1f06f0cd
Accept: application/json