GET http://127.0.0.1:8000/api/cliente-proveedor
Authorization: Bearer 67|DT8XuhVILsJj9ce8c6ZmK0r4N1NdQi1KpLhWWYWM636bb514
Accept: application/json

### Crear cliente proveedor
POST http://127.0.0.1:8000/api/cliente-proveedor
Authorization: Bearer 67|DT8XuhVILsJj9ce8c6ZmK0r4N1NdQi1KpLhWWYWM636bb514
Content-Type: application/json
Accept: application/json

{
    "tipo": "proveedor",
    "razon_social": "EMPRESA SAC",
    "nro_identificacion": "12345678",
    "telefono": "999999999",
    "direccion": "Av. Principal 123",
    "estado": "ACTIVO"
}

### Crear cliente
POST http://127.0.0.1:8000/api/cliente-proveedor
Authorization: Bearer 67|DT8XuhVILsJj9ce8c6ZmK0r4N1NdQi1KpLhWWYWM636bb514
Content-Type: application/json
Accept: application/json

{
    "tipo": "cliente",
    "razon_social": "Juan Perez",
    "nro_identificacion": "789456132",
    "telefono": "654321232",
    "direccion": "Av. Principal ABC Central",
    "estado": "ACTIVO"
}