### Lista sucursal
GET http://127.0.0.1:8000/api/sucursal
Authorization: Bearer 1|9BHOmOJhUsgqlNwFedRKEafLTmkbFeqRwUTc5sCC9c2b8315


### Crear sucursal
POST http://127.0.0.1:8000/api/sucursal
Authorization: Bearer 1|9BHOmOJhUsgqlNwFedRKEafLTmkbFeqRwUTc5sCC9c2b8315
Content-Type: application/json
Accept: application/json

{
    "nombre": "CENTRAL (Casa Matriz)",
    "direccion": "Av. 123 Zona ABC",
    "ciudad": "La Paz"
}
